stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "Running tests"

build:
  stage: build
  script: echo "Building the app"

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: 18.223.88.144
  only:
  - develop

deploy_production:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: production
    url: 3.16.170.160
  only:
  - master

