stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: "cd client && npm test"

deploy_staging:
  stage: deploy
  script:
    - ssh-add <(echo "$AWS_EC2_STAGING_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh ubuntu@AWS_EC2_STAGING_IP "if [[ -d \"~/arialpoint\" ]]; then git clone git@gitlab.com:code-care/arialpoint.git; fi && cd arialpoint && git checkout develop && git pull origin develop && exit"
  environment:
    name: staging
    url: 18.223.88.144
  only:
  - develop

deploy_production:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: production
    url: 3.16.170.160
  only:
  - master

