stages:
  - test
  - build
  - deploy

deploy_staging:
  stage: deploy
  script:
    - apt-get update -qq
    - apt-get install -qq git
    # Setup SSH deploy keys
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$AWS_EC2_STAGING_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - ssh ubuntu@$AWS_EC2_STAGING_IP "source local.env && cd arialpoint && git checkout develop && git pull origin develop && docker-compose down && docker-compose up --build -d && exit"
  environment:
    name: staging
    url: 18.223.88.144
  only:
  - develop

deploy_production:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: production
    url: 3.16.170.160
  only:
  - master


