version: "3.2"

services:
  server:
    volumes:
      - type: bind
        source: ./server
        target: /root/app/server
      - type: volume
        source: node_modules
        target: /root/app/server/node_modules
    command: bash -c './wait-for-it.sh mongodb:27017 -- touch logs/log && npm run dev'
    ports:
      - 3000:80

volumes:
  node_modules:
